#!/usr/bin/env sh

while getopts "t:x:rp:" option; do
  case "${option}" in
    x) EXECUTION_TAG=${OPTARG} ;;
    t) SCENARIO_TAG=${OPTARG} ;;
    r) REPORT=true ;;
    p) PROFILE=${OPTARG} ;;
  esac
done

function check_testexecution_id() {
  if [[ $EXECUTION_TAG != "" ]]; then
    ./xray -e -x ${EXECUTION_TAG}
  fi
}

if [[ $SCENARIO_TAG != "" ]]; then
  echo "Starting automation"
  echo "Running scenario with tag : ${SCENARIO_TAG}"
  check_testexecution_id
  godog --tags="${SCENARIO_TAG}" --format=cucumber > test/report/cucumber_report.json --random
  echo "Stopping automation"
  chmod 744 features/support/main/script.go
  ./features/support/main/script.go
  ./xray -i -j cucumber_report.json
else
  echo "Please define the running tag! ./godog -t '<tag_scenario>' or ./godog -r -t '<tag_scenario>' or ./godog -x <execution_id> -t '<tag_scenario>'"
  exit 1
fi

if [[ $REPORT == true ]]; then
  echo "Opening generate HTML report"
  node index.js
fi

if [[ $PROFILE != "" ]]; then
  # TODO
  # still on development
  echo $PROFILE
fi
