#!/usr/bin/env sh

while getopts "t:x:rp:" option; do
  case "${option}" in
    x) EXECUTION_TAG=${OPTARG} ;;
    t) SCENARIO_TAG=${OPTARG} ;;
    r) REPORT=true ;;
    p) PROFILE=${OPTARG} ;;
  esac
done

function check_testexecution_id() {
  if [[ $EXECUTION_TAG != "" ]]; then
    ./xray -e -f ${EXECUTION_TAG}
  fi
}

function start_automation_with_tag() {
  echo "Starting automation"
  echo "Running scenario with tag : ${SCENARIO_TAG}"
}

function start_automation_without_tag() {
  echo "Starting automation"
  echo "Running all of the scenario without @exclude tag"
}

function stop_automation() {
  echo "Stopping automation"
  # ./xray -i -j cucumber_report.json
  # chmod 744 features/support/scripts/main.go
  # ./features/support/scripts/main.go
}

function open_html_report() {
  if [[ $REPORT == true ]]; then
    echo "Opening generated HTML report"
    node index.js
  fi
}

if [[ $SCENARIO_TAG != "" ]]; then
  start_automation_with_tag
  check_testexecution_id
  godog --tags="${SCENARIO_TAG}" --format=cucumber > test/report/cucumber_report.json --random
  stop_automation
  open_html_report
else
  $REPORT=true

  start_automation_without_tag
  check_testexecution_id
  godog --tags=~@exclude --format=cucumber > test/report/cucumber_report.json --random
  stop_automation
  open_html_report
fi

if [[ $PROFILE != "" ]]; then
  # TODO : still on development
  echo $PROFILE
fi
