pipeline {
    agent any

    tools {
        go 'v1.17'
    }

    environment {
        GOROOT="/usr/local/go"
        GOPATH="$HOME/project/go"
        PATH="$PATH:$GOROOT/bin:$GOPATH/bin"
    }

    parameters {
        string(name: 'BRANCH', defaultValue: 'master', description: 'Please change repository branch')
        string(name: 'TAGS', defaultValue: '@scenarios', description: 'Please change scenario tags')
        booleanParam(name: 'IS_PR', defaultValue: true, description: 'Please change run purpose')
    }

    stages {
        stage('Checkout') {
            steps {
                echo 'Git Checkout'
                git branch: "${params.BRANCH}", url: 'https://golang-automation.git'
            }
        }

        stage('Install Dependencies') {
            steps {
                sh 'make deps'
            }
        }

        stage('Copy Sample File') {
            steps {
                sh 'make cp'
            }
        }

        stage('Test') {
            steps {
                echo 'Running test'
                sh "godog --tags=${params.TAGS} --format=cucumber > test/report/cucumber_report.json --random"
            }
        }
    }

    post {
        always {
            cucumber '**/cucumber_report.json'
        }
    }
}
