name: CI Workflow

on: [pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

  sonarCloudTrigger:
    needs: build
    name: SonarCloud Trigger
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
        - name: Analyze with SonarCloud
          uses: sonarsource/sonarcloud-github-action@master
          env:
            DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
            DANGER_SONAR_API_TOKEN: ${{ secrets.DANGER_SONAR_API_TOKEN }}

  dangerTrigger:
    needs: sonarCloudTrigger
    name: Danger Checker
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2
      - name: Set up Ruby 2.5
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.5.x
      - name: Execution
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
          DANGER_SONAR_API_TOKEN: ${{ secrets.DANGER_SONAR_API_TOKEN }}
        run: |
          bundle update
          bundle install
          bundle exec danger
