name: Ruby

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby 2.5.x
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.5.x
    - name: Danger setup
      uses: "actions/danger"
      with:
        DANGER_GITHUB_API_TOKEN: "${{ secrets.DANGER_GITHUB_API_TOKEN }}"
    - name: Danger checker
      run: |
        bundle update
        bundle install
        bundle exec danger
