name: Ruby

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Danger
      uses: "danger/danger"
    - name: Set up Ruby 2.5.x
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.5.x
    - name: Danger checker
      run: |
        bundle update
        bundle install
        bundle exec danger
